### ISSUE TITLE
Error when "npm run start"

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#5]
```
thomas@ThinkPad-Thomas:~/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port$ npm run start

> Sparnatural@3.0.0 start /home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port
> webpack-dev-server -d --hot --config webpack.config.js --watch

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/dist
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: 28882d81a9b491a4e037
Version: webpack 4.46.0
Time: 6365ms
Built at: 01/06/2022 11:35:12
                       Asset       Size  Chunks             Chunk Names
                   config.js   17.7 KiB          [emitted]  
                  index.html   6.31 KiB          [emitted]  
      sparnatural-config.rdf   1.35 KiB          [emitted]  
      sparnatural-config.ttl   1.04 KiB          [emitted]  
              sparnatural.js    859 KiB    main  [emitted]  main
stubs/treeChilds-ajson3.json  889 bytes          [emitted]  
         stubs/treeRoot.json  156 bytes          [emitted]  
     stubs/treeRoot_bak.json  702 bytes          [emitted]  
Entrypoint main = sparnatural.js
[1] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/yasgui/YasguiComponent.ts ./src/sparnatural.ts 64 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.52 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./src/sparnatural.ts] 701 bytes {main} [built] [failed] [1 error]
[./src/yasgui/YasguiComponent.ts] 2.63 KiB {main} [built] [failed] [1 error]
    + 23 hidden modules

ERROR in ./src/yasgui/YasguiComponent.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:42530:18)
    at /home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/servicesHost.js:679:18
    at /home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/servicesHost.js:118:141
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/servicesHost.js:118:124)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118278:21)
    at findSourceFile (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118133:26)
    at processImportedModules (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118539:25)
    at findSourceFileWorker (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118284:17)
    at findSourceFile (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118133:26)
    at processImportedModules (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118539:25)
    at findSourceFileWorker (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118284:17)
    at findSourceFile (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/typescript/lib/typescript.js:118133:26)
 @ multi ./src/yasgui/YasguiComponent.ts ./src/sparnatural.ts main[0]

ERROR in ./src/sparnatural.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'getSourceFile' of undefined
    at Object.getEmitOutput (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/instances.js:514:53)
    at getEmit (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/index.js:262:37)
    at successLoader (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/index.js:39:11)
    at Object.loader (/home/thomas/sparna/00-Clients/Sparna/20-Repositories/sparnatural-port/node_modules/ts-loader/dist/index.js:23:5)
 @ multi ./src/yasgui/YasguiComponent.ts ./src/sparnatural.ts main[1]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 6.65 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 531 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

```

**Comment by tfrancart** [comment]
Looking at it twice it seems related to `./src/yasgui/YasguiComponent.ts`, so could be related to the YasGui lib imported from here ?

**Comment by SteinerPascal** [comment]
I did setup an new virtual instance myself and got the same error. I'm looking at it right now. It looks like the ts loader was deprecated and webpack as well. but upgrading webpack kicks off a dependency wave. I'm now updating as much as possible and hope for the best =)

**Comment by SteinerPascal** [comment]
I just added some minor fixes. maybe you want to clone again

**Comment by tfrancart** [comment]
Works now
